DROP DATABASE IF EXISTS intellexDB;
CREATE DATABASE IF NOT EXISTS intellexDB;

USE intellexDB;

CREATE TABLE user(
    userID INT AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    verified TINYINT(1) DEFAULT 0,
    password VARCHAR(200) NOT NULL
);